#include "subsystems/Elevator.h"

Elevator::Elevator(Limelight *limelight3)
{
    this->limelight3 = limelight3;

    elevator1Motor.GetConfigurator().Apply(configs::TalonFXConfiguration{});
    configs::TalonFXConfiguration elevator1Config{};

    configs::MotorOutputConfigs elevator1MotorOutput{};
    elevator1MotorOutput.WithInverted(signals::InvertedValue::Clockwise_Positive);
    elevator1MotorOutput.WithNeutralMode(signals::NeutralModeValue::Brake);
    elevator1Config.WithMotorOutput(elevator1MotorOutput);

    elevator1Motor.GetConfigurator().Apply(elevator1Config);

    elevator2Motor.GetConfigurator().Apply(configs::TalonFXConfiguration{});
    configs::TalonFXConfiguration elevator2Config{};

    configs::MotorOutputConfigs elevator2MotorOutput{};
    elevator2MotorOutput.WithNeutralMode(signals::NeutralModeValue::Brake);
    elevator2Config.WithMotorOutput(elevator2MotorOutput);

    elevator2Motor.GetConfigurator().Apply(elevator2Config);

    frc::SmartDashboard::PutNumber("Elevator P", ElevatorConstants::kElevatorP);
    frc::SmartDashboard::PutNumber("Elevator I", ElevatorConstants::kElevatorI);
    frc::SmartDashboard::PutNumber("Elevator D", ElevatorConstants::kElevatorD);
    frc::SmartDashboard::PutNumber("Elevator F", ElevatorConstants::kElevatorF);

    frc::SmartDashboard::PutNumber("Elevator Speed", elevatorSpeed);
    frc::SmartDashboard::PutNumber("Elevator Amp Angle", ampAngle);
    shooterAngleEncoder.SetDistancePerRotation(-360);
}

void Elevator::Periodic()
{
    if (GetElevator1BottomLimit())
        ResetElevator1Encoder();
    if (GetElevator2BottomLimit())
        ResetElevator2Encoder();
    UpdateTelemetry();
}

// Returns the Angle from parallel to floor in degrees using limelight
double Elevator::CalculateSpeakerAngle()
{
    // Distance from speaker in meters
    auto distance = limelight3->GetDistanceFromTarget();
    // Height we are targetting in meters
    double targetHeight = ElevatorConstants::kSpeakerHeight + (((double)distance / ElevatorConstants::kForce) * ElevatorConstants::kGravity);
    // Get the angle we want to go to in order to shoot in radians, then converting it to degrees
    double targetAngle = atan(targetHeight / distance) * (180 / std::numbers::pi);
    // Adding the "Kickup" generated by the shooter and then returning that
    return -(targetAngle - ElevatorConstants::kKickup);
}

void Elevator::ElevatorControl(double angle)
{

        if (GetElevator1TopLimit() == false && GetElevator1BottomLimit() == false)
            SetElevator1MotorPosition(angle);
        else
            SetElevator1Motor(0.0);
        if (GetElevator2TopLimit() == false && GetElevator2BottomLimit() == false)
            SetElevator2MotorPosition(angle);
        else
            SetElevator2Motor(0.0);
}

void Elevator::UpdateTelemetry()
{
    frc::SmartDashboard::PutNumber("Shooter Angle Encoder Count", shooterAngleEncoder.GetAbsolutePosition());
    frc::SmartDashboard::PutNumber("Shooter Angle Degrees", GetShooterAngle()); 
    frc::SmartDashboard::PutNumber("Elevator 1 Encoder Pos", GetElevator1Encoder());
    frc::SmartDashboard::PutNumber("Elevator 2 Encoder Pos", GetElevator2Encoder());
    
}